### ISSUE TITLE
An adaptation of gmm_a which breaks symmetry

### ISSUE THREAD

**Issue by haohaiziround** [Tobias-Kohn/PyFOPPL-2#5]
Let's look a model which breaks the symmetry. 

```clojure
(def N 10)

(defn sample-components [_ zs pi]
  (let [z (sample (categorical pi))]
    (conj zs z)))

(defn get-ordered-mu [mu1 mu2]
  (if (< mu1 mu2)
    (vector mu1 mu2)
    (vector mu2 mu1)))

(defn observe-data [n _ ys zs mus]
  (let [y (get ys n)
        z (get zs n)
        mu (get mus z)]
    (observe (normal mu 1) y)
    nil))

(let [ys      (vector -2.0  -2.5  -1.7  -1.9  -2.2
                      1.5  2.2  3  1.2  2.8)
      pi [0.5 0.5]
      zs  (loop N (vector) sample-components pi)
      mu1 (sample (normal 0 100))   ; std = 10
      mu2 (sample (normal 0 100))
      mus (get-ordered-mu mu1 mu2)]
  (loop N nil observe-data ys zs mus)
  (vector mus zs))
```

I could compile it correctly but met a problem while running inference. Error message as following
```
ERROR in y30008:
  log_pdf += dist.Normal([state['x30005'], state['x30006']] if not ((state['x30005']-state['x30006'])>=0) else [state['x30006'], state['x30005']][runtime.index(state['x30002'])], 1).log_pdf(-2.0)
```
Is that something wrong with slicing or is it easy to adapt it?

**Comment by Tobias-Kohn** [comment]
I can guess what might have gone wrong here, but you need to provide the actual error message (in the example above you only gave the line that caused the error, but not the error message itself).

**Comment by Tobias-Kohn** [comment]
Just for the record: judging from the erroneous line, it seems there are parentheses missing, which something I can add rather easily. Simplified version of the code above:
```python
[a, b] if (...) else ([b, a] [i])
```
What it should look like:
```python
([a, b] if (...) else [b, a])[i]
```

**Comment by Tobias-Kohn** [comment]
I updated the code generator. Let me know if it works correctly now (I cannot do the inference on my end).

**Comment by bayesianbrad** [comment]
FIxed.
