### ISSUE TITLE
Getting a string back from dependent conditions

### ISSUE THREAD

**Issue by bayesianbrad** [Tobias-Kohn/PyFOPPL-2#6]
In branching BHMC I have to know which 'x***' corresponds to which 'cond_***'. I thought that accessing `vertex.dependent_conditions` would return the `str` name, which is what I need, but it actually returns the `set` from `condition` in `self.conditions`. But, you cannot access anything in this `set`, you can't even convert it a `list` and extract pieces of information as element 0, is just the whole condition. 
Is there another way to extract `dependent_conditions` as just a string?  I have a list of the 'cond_***' but at the moment you wouldn't be able to find which variable depends on it. 

The reason I require this information, is that when I am looking to see if a discontinuity has been crossed, I need both the `x` and the `cond` relating to that `x`, to extract a boolean from the `state` when the new, `state` has been generated. I was trying to create a hash map of `{vertex.name: vertex.dependent_condition}`, which I would then use within the inference.

**Comment by Tobias-Kohn** [comment]
`vertex.dependent_conditions` should a set of `ConditionNode`-objects. If you need the names, I would do the following:
```python
cond_names = [c.name for c in vertex.dependent_conditions]
```

**Comment by bayesianbrad** [comment]
That resolves the issue. 
Closed #6
